# TAP results for test_teardown_fixture_error_and_test_failure.py
not ok 1 - test_teardown_fixture_error_and_test_failure.py::test_fail
# 
#     def test_fail():
# >       assert 0, "failingfunc"
# E       AssertionError: failingfunc
# E       assert 0
# 
# test_teardown_fixture_error_and_test_failure.py:2: AssertionError
1..1
