# TAP results for test_capture_badoutput_issue412.py
not ok 1 - test_capture_badoutput_issue412.py::test_func
# 
#     def test_func():
#         omg = bytearray([1,129,1])
#         os.write(1, omg)
# >       assert 0
# E       assert 0
# 
# test_capture_badoutput_issue412.py:6: AssertionError
1..1
