# TAP results for test_maxfail.py
not ok 1 - test_maxfail.py::test_one
# 
# >   def test_one(): assert 0
# E   assert 0
# 
# test_maxfail.py:1: AssertionError
not ok 2 - test_maxfail.py::test_two
# 
# >   def test_two(): assert 0
# E   assert 0
# 
# test_maxfail.py:2: AssertionError
1..2
